[golerta]
    signing_key = "CHANGEME"
    auth_provider = "ldap"
    continuous_query_interval = "5s"

[ldap]
    host = "ldap.forumsys.com"
    port = 389
    base_dn = "dc=example,dc=com"
    bind_dn = "cn=read-only-admin,dc=example,dc=com"
    bind_password = "password"
    user_filter = "(uid=%s)"

[rethinkdb]
    address = "localhost:28015"
    database = "golerta"
    alert_history_limit = 100