[golerta]
    signing_key = "CHANGEME"
    auth_provider = "ldap"
    continuous_query_interval = "5s"

[ldap]
    host = "ldap.forumsys.com"
    port = 389
    base_dn = "dc=example,dc=com"
    bind_dn = "cn=read-only-admin,dc=example,dc=com"
    bind_password = "password"
    user_filter = "(uid=%s)"

[rethinkdb]
    address = "localhost:28015"
    database = "golerta"
    alert_history_limit = 100

[notifiers]
    trigger_severities = ["critical"]

[notifiers.file]
    enabled = true
    files = ["stdout"]

[notifiers.pagerduty]
    enabled = false
    service_key = "pagerduty service key here"